global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: helmet-api
    metrics_path: /metrics
    static_configs:
      - targets: ["app:8000"]
        labels:
          service: api

  - job_name: helmet-worker
    metrics_path: /metrics
    static_configs:
      - targets: ["worker:9100"]
        labels:
          service: worker
